### ISSUE TITLE
shell_command_after is without effect

### ISSUE THREAD

**Issue by lmignon** [tony/vcspull#17]
After  digging into the code, i've found a reference to a `shell_command_after` params but it seems never used. Do I miss something?

**Comment by tony** [comment]
@lmignon :

Sorry for the delay.

Correct you found a missing feature.  This is meant to run operation / scripts after a vcs is sync'd.

For example, if syncing a vim configuration on git, it could symlink a file.

It's probably best to remove the code for now though. Are you interested in making a PR?

**Comment by lmignon** [comment]
@tony Thank you for your reply. I've tested your script but it doesn't fit my needs. I was looking for a way to manage the aggregation of a lot of pending PR/branches in a reconciled one. I've finally developed my own script.
