### ISSUE TITLE
Using relative path for workspace path causes infinite recursion

### ISSUE THREAD

**Issue by jenisys** [tony/vcspull#28]
VERSION: vcspull 0.2.2

Using a relative path instead of an absolute path for the workspace root-dir seems to lead to infinite recursion after checkout of first project.

EXAMPLE: vcspull.yaml (needs: real Git repository)
```yaml
projects:
  foo: "git+https://github.com/the_user/foo.git"
```

```sh
$ vcspull -c vcspull.cfg co 
```

NOTE:
It would be nice to use the ``HERE`` idiom (the directory where the config-file is located).

**Comment by tony** [comment]
@jenisys this feature is front in line. soon.

**Comment by tony** [comment]
The parent directories in the next version will accept relative dirs. They will relative to the config file.

```
./projects/:
  foo: "git+https://github.com/the_user/foo.git"
```

**Comment by tony** [comment]
This should now work.   You can now populate projects relative to the config file location as well as trigger them via ``vcspull -c configfile``.

 If you are looking for any new behavior/functionality feel free to reopen this/a new issue.
